#!/bin/sh
#
# Wrapper script.  Run stupidart with any image format as input.
#
# Usage: stupidart-wrap [-<resize>] <input> [<output>]

resize="$1"
if echo "$resize" | grep -qE '^-'; then
    resize=" -resize $(echo "$resize" | cut -d- -f2)"
    shift
else
    resize=''
fi

input="$1"
if ! [ "$input" ]; then
    echo 'error: missing input image' > /dev/stderr
    exit 1
fi

output="$2"
if ! [ "$output" ]; then
    i=0
    output="out$i-$input.png"
    while test -f "$output"; do
        i=$(expr $i + 1)
        output="out$i-$input.png"
    done
fi

convert "$input$resize" pam:- | ./stupidart - - | convert pam:- "$output"
